name: guinea
channels:
  - pytorch
  - apple
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.2.3
  - openai=1.61.0
  - pip=24.2
  - pytorch
  - torchvision
  - torchaudio
  - pip:
      - python-dotenv==1.0.1
      - transformers>=4.15.0
      - pandas>=1.3.4
      - numpy>=1.21.4
      - scikit-learn>=1.0.1
      - scipy>=1.7.3
      - matplotlib>=3.5.0
      - requests>=2.26.0
